### PR TITLE
deprecated commands removed

### PR DESCRIPTION
**Pull request by bhadmus-lex**

### CODE REVIEW

**Review by npilon — CHANGES_REQUESTED** [review]
These API changes mean that the library now only works with `selenium >= 4.0.0` - `setup.py` should be adjusted to reflect this.

**Comment by npilon** [comment]
There's some further API incompatibilities:

```
nose2 -F planterbox_webdriver
..............E.E.F.......
======================================================================
ERROR: I exercise basic functionality of webdriver (planterbox_webdriver.tests.test_webdriver:basics.feature)
----------------------------------------------------------------------
Scenario: Test labels
    When I go to "basic_page"
    And I click on label "Password:"
    Then element with id "pass" should be focused
Traceback (most recent call last):
  File "/home/npilon/Documents/planterbox-webdriver_ve/lib/python3.9/site-packages/planterbox/feature.py", line 287, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/npilon/Documents/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 282, in element_focused
    focused = test.browser.switch_to_active_element()
AttributeError: 'WebDriver' object has no attribute 'switch_to_active_element'

======================================================================
ERROR: I exercise basic functionality of webdriver (planterbox_webdriver.tests.test_webdriver:basics.feature)
----------------------------------------------------------------------
Scenario: Submit only form
    When I go to "basic_page"
    And I submit the form with id "the-form"
Traceback (most recent call last):
  File "/home/npilon/Documents/planterbox-webdriver_ve/lib/python3.9/site-packages/planterbox/feature.py", line 287, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/npilon/Documents/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 335, in submit_form_id
    submit_form(form)
  File "/home/npilon/Documents/planterbox-webdriver/planterbox_webdriver/util.py", line 281, in submit_form
    if element._w3c:
AttributeError: 'WebElement' object has no attribute '_w3c'

======================================================================
FAIL: I exercise basic functionality of webdriver (planterbox_webdriver.tests.test_webdriver:basics.feature)
----------------------------------------------------------------------
Scenario: Test date input
    When I go to "basic_page"
    And I fill in "dob" with "1900/01/01"
    Then input "dob" has value "1900/01/01"
Traceback (most recent call last):
  File "/home/npilon/Documents/planterbox-webdriver_ve/lib/python3.9/site-packages/planterbox/feature.py", line 287, in run_scenario
    step_fn(self, *step_arguments)
  File "/home/npilon/Documents/planterbox-webdriver/planterbox_webdriver/webdriver.py", line 315, in input_has_value
    test.assertEqual(text_field.get_attribute('value'), value)
AssertionError: '' != '1900/01/01'
+ 1900/01/01

----------------------------------------------------------------------
Ran 26 tests in 26.546s

FAILED (failures=1, errors=2)```

File: planterbox_webdriver/util.py [hunk 1]
```diff
@@ -285,4 +285,4 @@ def submit_form(element):
             "e.initEvent('submit', true, true);"
             "arguments[0].dispatchEvent(e);", form)
     else:
-        element.submit()
+        element.click()
```
Comment (npilon) [inline planterbox_webdriver/util.py]: The problem here is that `._w3c` doesn't exist anymore - `AttributeError: 'WebElement' object has no attribute '_w3c'` - so we can't switch between strategies based on that. `.click()` seems like it won't work here, because this takes the form, not the submit button. I think we just want to eliminate the check and just have lines 282-286 as the entire body of this function.

Comment (bhadmus-lex) [reply planterbox_webdriver/util.py]: submit has been deprecated so `.click()` is what's left. I will research about this `._w3c` I am not familiar with it

Comment (npilon) [reply planterbox_webdriver/util.py]: Please do not research.

Comment (npilon) [reply planterbox_webdriver/util.py]: The `._w3c` check here was a hack for determining whether `.submit()` would work or not; with our new minimum `selenium` version dependency, we _know_ it won't, so we should _only_ use the solution from lines 282-286.

File: planterbox_webdriver/util.py [hunk 2]
```diff
@@ -277,11 +278,11 @@ def submit_form(element):
...
-    else:
-        element.submit()
+    # if element._w3c:
+    form = element.find_element(By.XPATH, "./ancestor-or-self::form")
+    element._parent.execute_script(
+        "var e = arguments[0].ownerDocument.createEvent('Event');"
+        "e.initEvent('submit', true, true);"
+        "arguments[0].dispatchEvent(e);", form)
+    # else:
+    #     element.click()
```
Comment (npilon) [inline planterbox_webdriver/util.py]: Can you remove the commented-out code here?

**Review by npilon — CHANGES_REQUESTED** [review]

**Review by npilon — APPROVED** [review]
Tests now pass under newest selenium.
